### ISSUE TITLE
moment("20111031","YYYYMMDD")のような使い方はありますか。

### ISSUE THREAD

**Issue by changkejun** [hrdaya/UltraDate.js#70]
和暦で探して、UltraDateを見つかりました。日付をフォーマットする機能にとてもすばらしいです。
フォーマット後の日付文字列をDateタイプに戻すparse処理も探しています。なぜならば、Ajaxで画面の入力日付をサーバに渡す場合、文字列のままなら、サーバ側で変換しなければなりません。javascriptで処理できればとおもいます。
いままでmomentの書き方しかみつかりません。UltraDateは、類似の使い方はあればぜひ教えてください。

**Comment by hrdaya** [comment]
@changkejun さん

残念ながらUltraDateではフォーマット後の日付文字列をDateタイプに戻すparse処理を実装していません。 :persevere: 
将来的には実装したいと考えていますので、実装までお待ちください。 :blush:
