### ISSUE TITLE
npmモジュールとしての配布の予定はありますか？

### ISSUE THREAD

**Issue by syossan27** [hrdaya/UltraDate.js#71]
こちらのUltraDate.jsですがnpmモジュールとしてnpmに登録されるご予定ありますでしょうか？

**Comment by iku000888** [comment]
非常に重宝させていただいているライブラリで、
npmモジュールとして利用できると更に使いやすくなるので是非ご検討ください。

:bowing_man:

**Comment by hrdaya** [comment]
ずいぶん遅くなりましたが、 `development` ブランチにUMD化したものを公開しました。
`npm` に登録はしていないので `"UltraDate.js": "git://github.com/hrdaya/UltraDate.js.git#development"`  を `package.json` に追加して　`npm install` すると `node_modules` 配下にインストールされます。
CommonJSで日本の設定を使うには下記のような感じで使用してください。
```
const DateJp = require('UltraDate/locale/ja');
let datejp = new DateJp();
```

Linter の設定等がまだうまくいっていないので `master` ブランチへのマージはしばらく先になりそうです。
ついでにTypeScript化しちゃおうかな…

**Comment by syossan27** [comment]
@hrdaya 
UMD化ご対応ありがとうございます！
一応こちらのISSUEはCloseとさせて頂きます。
ありがとうございました 🙇
